export const GMAIL_READONLY_SCOPE = "https://www.googleapis.com/auth/gmail.readonly";
type FetchImplementation = typeof fetch;
export interface GmailQuoteCandidate { messageId: string; threadId: string; receivedAt: string; from: string; subject: string; body: string; }
function decode(value = "") { try { return Buffer.from(value.replace(/-/g, "+").replace(/_/g, "/"), "base64").toString("utf8"); } catch { return ""; } }
function partText(part: any): string { if (part?.mimeType === "text/plain" && part.body?.data) return decode(part.body.data); return (part?.parts || []).map(partText).filter(Boolean).join("\n"); }
export class GmailQuotesClient {
  constructor(private readonly accessToken: string, private readonly fetchImpl: FetchImplementation = globalThis.fetch) {}
  private async request<T>(url: string) { const response = await this.fetchImpl(url, { headers: { Authorization: `Bearer ${this.accessToken}` } }); const result = await response.json().catch(() => ({})) as T & { error?: { message?: string } }; if (!response.ok) throw new Error(`GMAIL_REQUEST_FAILED:${result.error?.message || response.status}`); return result; }
  async listCandidates(after?: string) { const query = ["in:inbox", "-from:me", "-category:promotions", "-category:social", after ? `after:${Math.floor(new Date(after).getTime() / 1000)}` : "newer_than:90d"].join(" "); const list = await this.request<{ messages?: Array<{ id: string }> }>(`https://gmail.googleapis.com/gmail/v1/users/me/messages?maxResults=50&q=${encodeURIComponent(query)}`); const messages: GmailQuoteCandidate[] = []; for (const entry of list.messages || []) { const raw = await this.request<any>(`https://gmail.googleapis.com/gmail/v1/users/me/messages/${encodeURIComponent(entry.id)}?format=full`); const headers = new Map<string,string>((raw.payload?.headers || []).map((header: any) => [String(header.name).toLowerCase(), String(header.value)])); messages.push({ messageId: raw.id, threadId: raw.threadId, receivedAt: new Date(Number(raw.internalDate)).toISOString(), from: headers.get("from") || "", subject: headers.get("subject") || "(sem assunto)", body: partText(raw.payload) || decode(raw.payload?.body?.data) }); } return messages; }
}
export function classifyGmailQuoteCandidate(message: GmailQuoteCandidate) { const from = message.from.toLowerCase(); const content = `${message.subject}\n${message.body}`.toLowerCase(); if (/no-?reply|newsletter|mailchimp|notification|digest/.test(from + content.slice(0, 300))) return null; if (!/(or[çc]amento|proposta|pre[çc]o|quanto custa|budget|website|branding|identidade visual|marketing|seo|campanha|crm|automa[çc][aã]o|aplica[çc][aã]o)/i.test(content)) return null; const email = /<([^>]+@[^>]+)>/.exec(message.from)?.[1] || /([\w.+-]+@[\w.-]+\.[a-z]{2,})/i.exec(message.from)?.[1] || ""; const contact = message.from.replace(/<[^>]+>/, "").replace(/["']/g, "").trim(); return { companyName: contact || email.split("@")[1]?.split(".")[0] || "Contacto Gmail", contactName: contact, contactEmail: email.toLowerCase(), subject: message.subject, requestSummary: message.body.replace(/\s+/g, " ").trim().slice(0, 1200) || message.subject, classificationConfidence: 0.7 }; }
