import type { SupabaseClient } from "@supabase/supabase-js";
import type { Quote, QuoteAdjustment, QuoteItem, QuoteRequest, QuoteService } from "../types/quotes";
import { normalizeAdjustment, normalizeQuoteItem, validateQuoteInput, validateStatusTransition } from "./quoteCore";

type Row = Record<string, any>;
const now = () => new Date().toISOString();

export class QuoteStore {
  constructor(private readonly client: SupabaseClient) {}
  async workspaceId(userId: string) {
    const { data, error } = await this.client.from("workspace_members").select("workspace_id").eq("user_id", userId).eq("status", "active").single();
    if (error || !data) throw new Error("QUOTE_WORKSPACE_NOT_FOUND"); return data.workspace_id as string;
  }
  private request(row: Row): QuoteRequest { return { id: row.id, clientId: row.client_id, source: row.source, status: row.status, companyName: row.company_name, contactName: row.contact_name, contactEmail: row.contact_email, contactPhone: row.contact_phone, subject: row.subject, requestSummary: row.request_summary, serviceInterests: Array.isArray(row.service_interests) ? row.service_interests : [], budgetText: row.budget_text, deadlineText: row.deadline_text, notes: row.notes, ownerUserId: row.owner_user_id, gmailMessageId: row.gmail_message_id, gmailThreadId: row.gmail_thread_id, gmailReceivedAt: row.gmail_received_at, classificationConfidence: row.classification_confidence == null ? null : Number(row.classification_confidence), createdAt: row.created_at, updatedAt: row.updated_at }; }
  private item(row: Row): QuoteItem { return { id: row.id, category: row.category, name: row.name, description: row.description, pricingType: row.pricing_type, quantity: Number(row.quantity), unitAmountCents: Number(row.unit_amount_cents), billingInterval: row.billing_interval, performanceMetric: row.performance_metric, performanceRate: row.performance_rate == null ? null : Number(row.performance_rate), performanceBasis: row.performance_basis, attributionMethod: row.attribution_method, performanceConditions: row.performance_conditions, estimatedHours: row.estimated_hours == null ? null : Number(row.estimated_hours), internalCostCents: row.internal_cost_cents == null ? null : Number(row.internal_cost_cents), externalCostCents: row.external_cost_cents == null ? null : Number(row.external_cost_cents), included: row.included, sortOrder: row.sort_order }; }
  private adjustment(row: Row): QuoteAdjustment { return { id: row.id, label: row.label, type: row.type, target: row.target, value: Number(row.value), metadata: row.metadata || {}, sortOrder: row.sort_order }; }
  private quote(row: Row, items: QuoteItem[] = [], adjustments: QuoteAdjustment[] = []): Quote { return { id: row.id, requestId: row.request_id, clientId: row.client_id, reference: row.reference, status: row.status, companyName: row.company_name, contactName: row.contact_name, contactEmail: row.contact_email, title: row.title, summary: row.summary, currency: row.currency, validUntil: row.valid_until, commitmentMonths: row.commitment_months, paymentTerms: row.payment_terms, clientNotes: row.client_notes, internalNotes: row.internal_notes, ownerUserId: row.owner_user_id, items, adjustments, createdBy: row.created_by, sentAt: row.sent_at, acceptedAt: row.accepted_at, rejectedAt: row.rejected_at, createdAt: row.created_at, updatedAt: row.updated_at }; }
  private service(row: Row): QuoteService { return { id: row.id, name: row.name, category: row.category, description: row.description, pricingType: row.pricing_type, defaultAmountCents: row.default_amount_cents == null ? null : Number(row.default_amount_cents), defaultBillingInterval: row.default_billing_interval, estimatedHours: row.estimated_hours == null ? null : Number(row.estimated_hours), internalCostCents: row.internal_cost_cents == null ? null : Number(row.internal_cost_cents), active: row.active, sortOrder: row.sort_order, createdAt: row.created_at, updatedAt: row.updated_at }; }
  private async assertRelation(workspaceId: string, table: "clients" | "quote_requests", id?: string | null) { if (!id) return; const { data } = await this.client.from(table).select("id").eq("id", id).eq("workspace_id", workspaceId).maybeSingle(); if (!data) throw new Error("QUOTE_RELATION_INVALID"); }

  async listRequests(userId: string) { const workspaceId = await this.workspaceId(userId); const { data, error } = await this.client.from("quote_requests").select("*").eq("workspace_id", workspaceId).order("created_at", { ascending: false }); if (error) throw new Error(`QUOTE_REQUEST_READ_FAILED:${error.message}`); return (data || []).map((row) => this.request(row)); }
  async createRequest(userId: string, raw: Record<string, any>) { const workspaceId = await this.workspaceId(userId); await this.assertRelation(workspaceId, "clients", raw.clientId); const companyName = String(raw.companyName || "").trim(); const summary = String(raw.requestSummary || "").trim(); if (!companyName || !summary) throw new Error("Empresa e resumo do pedido são obrigatórios."); const { data, error } = await this.client.from("quote_requests").insert({ workspace_id: workspaceId, client_id: raw.clientId || null, source: String(raw.source || "manual"), status: raw.status || "new", company_name: companyName, contact_name: String(raw.contactName || ""), contact_email: String(raw.contactEmail || "").trim().toLowerCase(), contact_phone: String(raw.contactPhone || ""), subject: String(raw.subject || ""), request_summary: summary, service_interests: Array.isArray(raw.serviceInterests) ? raw.serviceInterests : [], budget_text: String(raw.budgetText || ""), deadline_text: String(raw.deadlineText || ""), notes: String(raw.notes || ""), owner_user_id: raw.ownerUserId || userId, gmail_message_id: raw.gmailMessageId || null, gmail_thread_id: raw.gmailThreadId || null, gmail_received_at: raw.gmailReceivedAt || null, classification_confidence: raw.classificationConfidence ?? null, created_by: raw.gmailMessageId ? null : userId }).select("*").single(); if (error || !data) throw new Error(`QUOTE_REQUEST_CREATE_FAILED:${error?.message}`); return this.request(data); }
  async updateRequest(userId: string, id: string, raw: Record<string, any>) { const workspaceId = await this.workspaceId(userId); const { data: current } = await this.client.from("quote_requests").select("*").eq("id", id).eq("workspace_id", workspaceId).single(); if (!current) throw new Error("QUOTE_REQUEST_NOT_FOUND"); if (raw.status) validateStatusTransition("request", current.status, raw.status); await this.assertRelation(workspaceId, "clients", raw.clientId); const patch: Row = { updated_at: now() }; const map: Record<string,string> = { clientId:"client_id",source:"source",status:"status",companyName:"company_name",contactName:"contact_name",contactEmail:"contact_email",contactPhone:"contact_phone",subject:"subject",requestSummary:"request_summary",serviceInterests:"service_interests",budgetText:"budget_text",deadlineText:"deadline_text",notes:"notes",ownerUserId:"owner_user_id" }; for (const [key,column] of Object.entries(map)) if (key in raw) patch[column] = raw[key] || (key === "clientId" || key === "ownerUserId" ? null : raw[key]); const { data, error } = await this.client.from("quote_requests").update(patch).eq("id", id).eq("workspace_id", workspaceId).select("*").single(); if (error || !data) throw new Error(`QUOTE_REQUEST_UPDATE_FAILED:${error?.message}`); return this.request(data); }

  async listQuotes(userId: string) { const workspaceId = await this.workspaceId(userId); const [{ data: rows, error }, { data: items }, { data: adjustments }] = await Promise.all([this.client.from("quotes").select("*").eq("workspace_id", workspaceId).order("created_at", { ascending: false }), this.client.from("quote_items").select("*").eq("workspace_id", workspaceId).order("sort_order"), this.client.from("quote_adjustments").select("*").eq("workspace_id", workspaceId).order("sort_order")]); if (error) throw new Error(`QUOTE_READ_FAILED:${error.message}`); return (rows || []).map((row) => this.quote(row, (items || []).filter((item) => item.quote_id === row.id).map((item) => this.item(item)), (adjustments || []).filter((item) => item.quote_id === row.id).map((item) => this.adjustment(item)))); }
  async getQuote(userId: string, id: string) { const quotes = await this.listQuotes(userId); const quote = quotes.find((item) => item.id === id); if (!quote) throw new Error("QUOTE_NOT_FOUND"); return quote; }
  private quoteRow(workspaceId: string, input: any, userId: string, reference?: string) { return { workspace_id: workspaceId, request_id: input.requestId || null, client_id: input.clientId || null, ...(reference ? { reference } : {}), status: input.status || "draft", company_name: input.companyName, contact_name: input.contactName, contact_email: input.contactEmail, title: input.title, summary: input.summary, currency: input.currency, valid_until: input.validUntil || null, commitment_months: input.commitmentMonths, payment_terms: input.paymentTerms, client_notes: input.clientNotes, internal_notes: input.internalNotes, owner_user_id: input.ownerUserId || userId, updated_at: now() }; }
  private async replaceChildren(workspaceId: string, quoteId: string, items: QuoteItem[], adjustments: QuoteAdjustment[]) { await Promise.all([this.client.from("quote_items").delete().eq("quote_id", quoteId).eq("workspace_id", workspaceId), this.client.from("quote_adjustments").delete().eq("quote_id", quoteId).eq("workspace_id", workspaceId)]); if (items.length) { const { error } = await this.client.from("quote_items").insert(items.map((item) => ({ quote_id: quoteId, workspace_id: workspaceId, category: item.category, name: item.name, description: item.description, pricing_type: item.pricingType, quantity: item.quantity, unit_amount_cents: item.unitAmountCents, billing_interval: item.billingInterval || null, performance_metric: item.performanceMetric || "", performance_rate: item.performanceRate ?? null, performance_basis: item.performanceBasis || "", attribution_method: item.attributionMethod || "", performance_conditions: item.performanceConditions || "", estimated_hours: item.estimatedHours ?? null, internal_cost_cents: item.internalCostCents ?? null, external_cost_cents: item.externalCostCents ?? null, included: item.included, sort_order: item.sortOrder }))); if (error) throw new Error(`QUOTE_ITEMS_WRITE_FAILED:${error.message}`); } if (adjustments.length) { const { error } = await this.client.from("quote_adjustments").insert(adjustments.map((item) => ({ quote_id: quoteId, workspace_id: workspaceId, label: item.label, type: item.type, target: item.target, value: item.value, metadata: item.metadata || {}, sort_order: item.sortOrder }))); if (error) throw new Error(`QUOTE_ADJUSTMENTS_WRITE_FAILED:${error.message}`); } }
  async createQuote(userId: string, raw: Record<string, any>) { const workspaceId = await this.workspaceId(userId); const input = validateQuoteInput(raw); await this.assertRelation(workspaceId, "clients", input.clientId); await this.assertRelation(workspaceId, "quote_requests", input.requestId); const { data: reference, error: referenceError } = await this.client.rpc("next_quote_reference", { target_workspace_id: workspaceId }); if (referenceError || !reference) throw new Error(`QUOTE_REFERENCE_FAILED:${referenceError?.message}`); const { data, error } = await this.client.from("quotes").insert({ ...this.quoteRow(workspaceId, input, userId, reference), created_by: userId }).select("*").single(); if (error || !data) throw new Error(`QUOTE_CREATE_FAILED:${error?.message}`); await this.replaceChildren(workspaceId, data.id, input.items, input.adjustments); if (input.requestId) await this.client.from("quote_requests").update({ status: "converted", updated_at: now() }).eq("id", input.requestId).eq("workspace_id", workspaceId); return this.getQuote(userId, data.id); }
  async updateQuote(userId: string, id: string, raw: Record<string, any>) { const workspaceId = await this.workspaceId(userId); const current = await this.getQuote(userId, id); if (!["draft","ready"].includes(current.status)) throw new Error("Só podes editar orçamentos em rascunho ou prontos."); const input = validateQuoteInput({ ...current, ...raw }); await this.assertRelation(workspaceId, "clients", input.clientId); const { error } = await this.client.from("quotes").update(this.quoteRow(workspaceId, input, userId)).eq("id", id).eq("workspace_id", workspaceId); if (error) throw new Error(`QUOTE_UPDATE_FAILED:${error.message}`); await this.replaceChildren(workspaceId, id, input.items, input.adjustments); return this.getQuote(userId, id); }
  async changeStatus(userId: string, id: string, status: Quote["status"]) { const workspaceId = await this.workspaceId(userId); const current = await this.getQuote(userId, id); validateStatusTransition("quote", current.status, status); const stamp: Row = { status, updated_at: now() }; if (status === "sent") stamp.sent_at = now(); if (status === "accepted") stamp.accepted_at = now(); if (status === "rejected") stamp.rejected_at = now(); const { error } = await this.client.from("quotes").update(stamp).eq("id", id).eq("workspace_id", workspaceId); if (error) throw new Error(`QUOTE_STATUS_FAILED:${error.message}`); return this.getQuote(userId, id); }
  async duplicate(userId: string, id: string) { const quote = await this.getQuote(userId, id); return this.createQuote(userId, { ...quote, id: undefined, requestId: null, title: `${quote.title} — cópia`, status: "draft", items: quote.items.map(({ id: _id, ...item }) => item), adjustments: quote.adjustments.map(({ id: _id, ...item }) => item) }); }
  async remove(userId: string, id: string) { const workspaceId = await this.workspaceId(userId); const current = await this.getQuote(userId, id); if (!["draft","cancelled"].includes(current.status)) throw new Error("Apenas rascunhos ou cancelados podem ser eliminados."); const { error } = await this.client.from("quotes").delete().eq("id", id).eq("workspace_id", workspaceId); if (error) throw new Error(`QUOTE_DELETE_FAILED:${error.message}`); }

  async listServices(userId: string) { const workspaceId = await this.workspaceId(userId); const { data, error } = await this.client.from("quote_services").select("*").eq("workspace_id", workspaceId).order("sort_order"); if (error) throw new Error(`QUOTE_SERVICE_READ_FAILED:${error.message}`); return (data || []).map((row) => this.service(row)); }
  async listMembers(userId: string) { const workspaceId = await this.workspaceId(userId); const [{ data: memberships, error: memberError }, { data: profiles, error: profileError }] = await Promise.all([this.client.from("workspace_members").select("user_id").eq("workspace_id", workspaceId).eq("status", "active"), this.client.from("profiles").select("user_id,preferred_name,display_name,email").eq("workspace_id", workspaceId)]); if (memberError || profileError) throw new Error(`QUOTE_MEMBER_READ_FAILED:${(memberError || profileError)?.message}`); const active = new Set((memberships || []).map((entry) => entry.user_id)); return (profiles || []).filter((profile) => active.has(profile.user_id)).map((profile) => ({ userId: profile.user_id, name: profile.preferred_name || profile.display_name || profile.email, email: profile.email })); }
  async saveService(userId: string, raw: Record<string, any>, id?: string) { const workspaceId = await this.workspaceId(userId); const item = normalizeQuoteItem({ name: raw.name, category: raw.category, description: raw.description, pricingType: raw.pricingType, quantity: 1, unitAmountCents: raw.defaultAmountCents || 0, billingInterval: raw.defaultBillingInterval, estimatedHours: raw.estimatedHours, internalCostCents: raw.internalCostCents }); const row = { workspace_id: workspaceId, name: item.name, category: item.category, description: item.description, pricing_type: item.pricingType, default_amount_cents: raw.defaultAmountCents == null ? null : item.unitAmountCents, default_billing_interval: item.billingInterval, estimated_hours: item.estimatedHours, internal_cost_cents: item.internalCostCents, active: raw.active !== false, sort_order: Number(raw.sortOrder) || 0, updated_at: now() }; const query = id ? this.client.from("quote_services").update(row).eq("id", id).eq("workspace_id", workspaceId) : this.client.from("quote_services").insert(row); const { data, error } = await query.select("*").single(); if (error || !data) throw new Error(`QUOTE_SERVICE_WRITE_FAILED:${error?.message}`); return this.service(data); }
  async removeService(userId: string, id: string) { const workspaceId = await this.workspaceId(userId); const { error } = await this.client.from("quote_services").delete().eq("id", id).eq("workspace_id", workspaceId); if (error) throw new Error(`QUOTE_SERVICE_DELETE_FAILED:${error.message}`); }
}
