import React, { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowLeft, Check, Copy, FileText, Mail, Plus, RefreshCw, Search, Trash2, X } from "lucide-react";
import type { AccentColorOption } from "../../types/settings";
import type { Quote, QuoteRequest, QuoteRequestStatus, QuoteService, QuoteStatus, QuotesPayload } from "../../types/quotes";
import QuoteEditor, { type QuoteDraft } from "./QuoteEditor";

type View = "requests" | "quotes" | "catalog";
const inputClass="w-full rounded-xl border border-white/10 bg-black/25 px-3 py-2 text-sm text-white outline-none focus:border-cyan-300/40";
const requestLabels:Record<QuoteRequestStatus,string>={new:"Novo",reviewing:"Em análise",qualified:"Qualificado",converted:"Convertido",discarded:"Descartado"};
const quoteLabels:Record<QuoteStatus,string>={draft:"Rascunho",ready:"Pronto",sent:"Enviado",accepted:"Aceite",rejected:"Rejeitado",expired:"Expirado",cancelled:"Cancelado"};
const freshQuote=(request?:QuoteRequest):QuoteDraft=>({requestId:request?.id||null,clientId:request?.clientId||null,status:"draft",companyName:request?.companyName||"",contactName:request?.contactName||"",contactEmail:request?.contactEmail||"",title:request?.subject||"",summary:request?.requestSummary||"",currency:"EUR",validUntil:"",commitmentMonths:null,paymentTerms:"",clientNotes:"",internalNotes:request?.notes||"",items:[],adjustments:[]});

async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{...init,headers:{"Content-Type":"application/json",...init?.headers}});const value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(value.error||"Não foi possível concluir a operação.");return value}

export default function QuotesScreen({accentColor,onBackToOverview}:{accentColor:AccentColorOption;onBackToOverview:()=>void}){
 const [payload,setPayload]=useState<QuotesPayload>({requests:[],quotes:[],services:[]}); const [clients,setClients]=useState<any[]>([]); const [view,setView]=useState<View>("requests"); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [search,setSearch]=useState(""); const [editor,setEditor]=useState<QuoteDraft|null>(null); const [requestModal,setRequestModal]=useState(false); const [catalogModal,setCatalogModal]=useState<QuoteService|"new"|null>(null); const [saving,setSaving]=useState(false); const [gmail,setGmail]=useState<any>(null); const [syncing,setSyncing]=useState(false);
 const load=useCallback(async()=>{try{setError("");const [data,gmailStatus,clientData]=await Promise.all([api<QuotesPayload>("/api/quotes"),api<any>("/api/quotes/gmail/status").catch(()=>null),api<{clients:any[]}>("/api/clients").catch(()=>({clients:[]}))]);setPayload(data);setGmail(gmailStatus);setClients(clientData.clients||[])}catch(e){setError(e instanceof Error?e.message:"Falha ao carregar.")}finally{setLoading(false)}},[]);
 useEffect(()=>{void load();const listener=(event:Event)=>{const table=(event as CustomEvent).detail?.table;if(["quotes","quote_requests","quote_services"].includes(table))void load()};window.addEventListener("axion:realtime",listener);return()=>window.removeEventListener("axion:realtime",listener)},[load]);
 const filteredRequests=useMemo(()=>payload.requests.filter((item)=>`${item.companyName} ${item.contactName} ${item.subject}`.toLowerCase().includes(search.toLowerCase())),[payload.requests,search]);
 const filteredQuotes=useMemo(()=>payload.quotes.filter((item)=>`${item.reference} ${item.companyName} ${item.title}`.toLowerCase().includes(search.toLowerCase())),[payload.quotes,search]);
 const saveQuote=async(draft:QuoteDraft)=>{setSaving(true);try{if(draft.id)await api(`/api/quotes/${draft.id}`,{method:"PUT",body:JSON.stringify(draft)});else await api("/api/quotes",{method:"POST",body:JSON.stringify(draft)});setEditor(null);await load()}catch(e){setError(e instanceof Error?e.message:"Não foi possível guardar.")}finally{setSaving(false)}};
 const changeStatus=async(quote:Quote,status:QuoteStatus)=>{try{await api(`/api/quotes/${quote.id}/status`,{method:"POST",body:JSON.stringify({status})});await load()}catch(e){setError(e instanceof Error?e.message:"Falha ao atualizar estado.")}};
 const sync=async()=>{setSyncing(true);try{const result=await api<{imported:number}>("/api/quotes/gmail/sync",{method:"POST"});setError(result.imported?`${result.imported} novo(s) pedido(s) importado(s).`:"Gmail sincronizado. Não existem pedidos novos.");await load()}catch(e){setError(e instanceof Error?e.message:"Falha na sincronização.")}finally{setSyncing(false)}};
 if(editor)return <QuoteEditor initial={editor} services={payload.services} clients={clients} saving={saving} onSave={saveQuote} onBack={()=>setEditor(null)}/>;
 return <div className="min-h-full pb-20"><header className="mb-7 flex flex-wrap items-end justify-between gap-4"><div><button onClick={onBackToOverview} className="mb-4 flex items-center gap-2 text-[10px] uppercase tracking-wider text-white/35 hover:text-white"><ArrowLeft size={14}/>Painel principal</button><p className="text-[10px] font-mono uppercase tracking-[.28em]" style={{color:accentColor.hex}}>Pipeline comercial</p><h1 className="mt-2 text-3xl font-semibold">Orçamentos</h1><p className="mt-2 max-w-2xl text-sm text-white/40">Pedidos, propostas, preços e margem num único fluxo comercial.</p></div><div className="flex gap-2"><button onClick={()=>setRequestModal(true)} className="rounded-xl border border-white/10 px-4 py-2 text-xs text-white/70"><Plus size={14} className="mr-1 inline"/>Novo pedido</button><button onClick={()=>setEditor(freshQuote())} className="rounded-xl px-4 py-2 text-xs font-semibold text-slate-950" style={{background:accentColor.hex}}><Plus size={14} className="mr-1 inline"/>Novo orçamento</button></div></header>
 {error&&<div className="mb-5 flex items-center justify-between rounded-2xl border border-cyan-300/15 bg-cyan-300/[.05] px-4 py-3 text-xs text-white/65"><span>{error}</span><button onClick={()=>setError("")}><X size={14}/></button></div>}
 <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div className="flex rounded-2xl border border-white/10 bg-black/20 p-1">{(["requests","quotes","catalog"] as View[]).map((item)=><button key={item} onClick={()=>setView(item)} className={`rounded-xl px-4 py-2 text-xs ${view===item?"bg-white/10 text-white":"text-white/40"}`}>{item==="requests"?`Pedidos · ${payload.requests.length}`:item==="quotes"?`Orçamentos · ${payload.quotes.length}`:`Catálogo · ${payload.services.length}`}</button>)}</div>{view!=="catalog"&&<label className="relative"><Search size={14} className="absolute left-3 top-2.5 text-white/25"/><input className="rounded-xl border border-white/10 bg-black/25 py-2 pl-9 pr-3 text-xs outline-none" placeholder="Pesquisar…" value={search} onChange={(e)=>setSearch(e.target.value)}/></label>}</div>
 {loading ? <Empty text="A carregar dados comerciais…"/> : view === "requests" ? <div className="space-y-4">
   <GmailCard gmail={gmail} syncing={syncing} onSync={sync}/>
   {filteredRequests.length === 0 ? <Empty text="Ainda não existem pedidos de orçamento."/> : <div className="grid gap-3 xl:grid-cols-2">{filteredRequests.map((request) => <div key={request.id}><RequestCard request={request} onUpdate={async(status)=>{await api(`/api/quotes/requests/${request.id}`,{method:"PUT",body:JSON.stringify({status})});await load()}} onConvert={()=>setEditor(freshQuote(request))}/></div>)}</div>}
 </div> : view === "quotes" ? <div>
   {filteredQuotes.length === 0 ? <Empty text="Ainda não existem orçamentos."/> : <div className="grid gap-3 xl:grid-cols-2">{filteredQuotes.map((quote) => <div key={quote.id}><QuoteCard quote={quote} onOpen={()=>setEditor(quote)} onDuplicate={async()=>{await api(`/api/quotes/${quote.id}/duplicate`,{method:"POST"});await load()}} onStatus={(status)=>changeStatus(quote,status)}/></div>)}</div>}
 </div> : <Catalog services={payload.services} onNew={()=>setCatalogModal("new")} onEdit={setCatalogModal} onDelete={async(id)=>{await api(`/api/quotes/services/${id}`,{method:"DELETE"});await load()}}/>}
 {requestModal&&<RequestModal onClose={()=>setRequestModal(false)} onSave={async(value)=>{setSaving(true);try{await api("/api/quotes/requests",{method:"POST",body:JSON.stringify(value)});setRequestModal(false);await load()}catch(e){setError(e instanceof Error?e.message:"Falha.")}finally{setSaving(false)}}} saving={saving}/>} {catalogModal&&<ServiceModal initial={catalogModal==="new"?null:catalogModal} onClose={()=>setCatalogModal(null)} saving={saving} onSave={async(value)=>{setSaving(true);try{await api(catalogModal==="new"?"/api/quotes/services":`/api/quotes/services/${catalogModal.id}`,{method:catalogModal==="new"?"POST":"PUT",body:JSON.stringify(value)});setCatalogModal(null);await load()}catch(e){setError(e instanceof Error?e.message:"Falha.")}finally{setSaving(false)}}}/>} 
 </div>
}

function GmailCard({gmail,syncing,onSync}:{gmail:any;syncing:boolean;onSync:()=>void}){
  const status = gmail?.connected
    ? `${gmail.email} · ${gmail.lastSyncAt ? `última sync ${new Date(gmail.lastSyncAt).toLocaleString("pt-PT")}` : "ainda não sincronizado"}`
    : gmail?.configured ? `Liga ${gmail.expectedEmail} para importar pedidos reais.` : "Integração ainda sem configuração externa.";
  return <div className="flex flex-wrap items-center justify-between gap-3 rounded-3xl border border-white/10 bg-[#0c1017]/75 p-4"><div className="flex items-center gap-3"><span className="rounded-2xl bg-white/5 p-3"><Mail size={18}/></span><div><p className="text-sm font-medium">Gmail comercial</p><p className="text-[11px] text-white/35">{status}</p></div></div>{gmail?.connected?<button disabled={syncing} onClick={onSync} className="rounded-xl border border-white/10 px-3 py-2 text-xs"><RefreshCw size={13} className={`mr-1 inline ${syncing?"animate-spin":""}`}/>Sincronizar agora</button>:gmail?.configured?<button onClick={()=>window.location.assign("/api/quotes/gmail/oauth/start")} className="rounded-xl border border-white/10 px-3 py-2 text-xs">Ligar Gmail partilhado</button>:null}</div>
}
function RequestCard({request,onUpdate,onConvert}:{request:QuoteRequest;onUpdate:(status:QuoteRequestStatus)=>void;onConvert:()=>void}){return <article className="rounded-3xl border border-white/10 bg-[#0c1017]/80 p-5"><div className="flex items-start justify-between gap-3"><div><span className="text-[9px] uppercase tracking-wider text-cyan-200/45">{request.source}</span><h3 className="mt-1 text-lg font-medium">{request.companyName}</h3><p className="text-xs text-white/35">{request.contactName}{request.contactEmail?` · ${request.contactEmail}`:""}</p></div><Badge>{requestLabels[request.status]}</Badge></div><h4 className="mt-4 text-sm">{request.subject||"Pedido comercial"}</h4><p className="mt-2 line-clamp-3 text-xs leading-5 text-white/45">{request.requestSummary}</p><div className="mt-4 flex flex-wrap gap-2">{request.status!=="converted"&&<><select value={request.status} onChange={(e)=>onUpdate(e.target.value as QuoteRequestStatus)} className="rounded-xl border border-white/10 bg-black/30 px-3 py-2 text-xs"><option value="new">Novo</option><option value="reviewing">Em análise</option><option value="qualified">Qualificado</option><option value="discarded">Descartado</option></select><button onClick={onConvert} className="rounded-xl bg-cyan-300 px-3 py-2 text-xs font-semibold text-slate-950">Criar orçamento</button></>}</div></article>}
function QuoteCard({quote,onOpen,onDuplicate,onStatus}:{quote:Quote;onOpen:()=>void;onDuplicate:()=>void;onStatus:(status:QuoteStatus)=>void}){const next:Partial<Record<QuoteStatus,QuoteStatus[]>>={draft:["ready","cancelled"],ready:["draft","sent","cancelled"],sent:["accepted","rejected","expired","cancelled"],rejected:["draft"],expired:["draft"],cancelled:["draft"]};return <article className="rounded-3xl border border-white/10 bg-[#0c1017]/80 p-5"><div className="flex justify-between gap-3"><div><p className="font-mono text-[10px] text-cyan-200/55">{quote.reference}</p><h3 className="mt-1 text-lg font-medium">{quote.title}</h3><p className="text-xs text-white/35">{quote.companyName}</p></div><Badge>{quoteLabels[quote.status]}</Badge></div><p className="mt-4 line-clamp-2 text-xs leading-5 text-white/45">{quote.summary||"Sem resumo."}</p><div className="mt-4 flex flex-wrap gap-2"><button onClick={onOpen} className="rounded-xl border border-white/10 px-3 py-2 text-xs"><FileText size={13} className="mr-1 inline"/>Abrir</button><button onClick={onDuplicate} className="rounded-xl border border-white/10 px-3 py-2 text-xs"><Copy size={13} className="mr-1 inline"/>Duplicar</button>{(next[quote.status]||[]).map((status)=><button key={status} onClick={()=>onStatus(status)} className="rounded-xl border border-cyan-300/15 px-3 py-2 text-xs text-cyan-100/70">{quoteLabels[status]}</button>)}</div></article>}
function Catalog({services,onNew,onEdit,onDelete}:{services:QuoteService[];onNew:()=>void;onEdit:(service:QuoteService)=>void;onDelete:(id:string)=>void}){return <div><div className="mb-4 flex justify-end"><button onClick={onNew} className="rounded-xl border border-white/10 px-4 py-2 text-xs"><Plus size={13} className="mr-1 inline"/>Novo serviço</button></div>{services.length===0?<Empty text="O catálogo está vazio. Adiciona serviços sem preços inventados."/>:<div className="overflow-hidden rounded-3xl border border-white/10"><table className="w-full text-left text-xs"><thead className="bg-white/[.04] text-white/35"><tr><th className="p-4">Serviço</th><th>Categoria</th><th>Modelo</th><th>Preço base</th><th/></tr></thead><tbody>{services.map((service)=><tr key={service.id} className="border-t border-white/8"><td className="p-4 font-medium">{service.name}</td><td className="text-white/45">{service.category||"—"}</td><td className="text-white/45">{service.pricingType}</td><td className="text-white/45">{service.defaultAmountCents==null?"A definir":`${(service.defaultAmountCents/100).toFixed(2)} €`}</td><td className="pr-3 text-right"><button onClick={()=>onEdit(service)} className="p-2 text-white/50">Editar</button><button onClick={()=>onDelete(service.id)} className="p-2 text-rose-300/60"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>}</div>}
function RequestModal({onClose,onSave,saving}:{onClose:()=>void;onSave:(value:any)=>void;saving:boolean}){const [value,setValue]=useState<any>({companyName:"",contactName:"",contactEmail:"",contactPhone:"",source:"manual",subject:"",requestSummary:"",serviceInterests:[],budgetText:"",deadlineText:"",notes:""});return <Modal title="Novo pedido" onClose={onClose}><div className="grid gap-3 md:grid-cols-2"><Field label="Empresa *"><input className={inputClass} value={value.companyName} onChange={(e)=>setValue({...value,companyName:e.target.value})}/></Field><Field label="Origem"><select className={inputClass} value={value.source} onChange={(e)=>setValue({...value,source:e.target.value})}><option value="manual">Manual</option><option value="phone">Telefone</option><option value="cold_call">Cold call</option><option value="referral">Referral</option><option value="website">Website</option></select></Field><Field label="Contacto"><input className={inputClass} value={value.contactName} onChange={(e)=>setValue({...value,contactName:e.target.value})}/></Field><Field label="Email"><input className={inputClass} value={value.contactEmail} onChange={(e)=>setValue({...value,contactEmail:e.target.value})}/></Field><Field label="Telefone"><input className={inputClass} value={value.contactPhone} onChange={(e)=>setValue({...value,contactPhone:e.target.value})}/></Field><Field label="Assunto"><input className={inputClass} value={value.subject} onChange={(e)=>setValue({...value,subject:e.target.value})}/></Field><Field label="Budget informado"><input className={inputClass} value={value.budgetText} onChange={(e)=>setValue({...value,budgetText:e.target.value})}/></Field><Field label="Deadline informado"><input className={inputClass} value={value.deadlineText} onChange={(e)=>setValue({...value,deadlineText:e.target.value})}/></Field></div><Field label="Resumo do pedido *"><textarea rows={4} className={inputClass} value={value.requestSummary} onChange={(e)=>setValue({...value,requestSummary:e.target.value})}/></Field><Field label="Notas"><textarea rows={3} className={inputClass} value={value.notes} onChange={(e)=>setValue({...value,notes:e.target.value})}/></Field><Actions saving={saving} onClose={onClose} onSave={()=>onSave(value)}/></Modal>}
function ServiceModal({initial,onClose,onSave,saving}:{initial:QuoteService|null;onClose:()=>void;onSave:(value:any)=>void;saving:boolean}){const [value,setValue]=useState<any>(initial||{name:"",category:"",description:"",pricingType:"project",defaultAmountCents:null,defaultBillingInterval:null,estimatedHours:null,internalCostCents:null,active:true,sortOrder:0});return <Modal title={initial?"Editar serviço":"Novo serviço"} onClose={onClose}><div className="grid gap-3 md:grid-cols-2"><Field label="Nome *"><input className={inputClass} value={value.name} onChange={(e)=>setValue({...value,name:e.target.value})}/></Field><Field label="Categoria"><input className={inputClass} value={value.category} onChange={(e)=>setValue({...value,category:e.target.value})}/></Field><Field label="Modelo"><select className={inputClass} value={value.pricingType} onChange={(e)=>setValue({...value,pricingType:e.target.value,defaultBillingInterval:e.target.value==="recurring"?(value.defaultBillingInterval||"monthly"):null})}><option value="project">Projeto</option><option value="recurring">Recorrente</option><option value="performance">Performance</option></select></Field>{value.pricingType==="recurring"&&<Field label="Periodicidade"><select className={inputClass} value={value.defaultBillingInterval||"monthly"} onChange={(e)=>setValue({...value,defaultBillingInterval:e.target.value})}><option value="monthly">Mensal</option><option value="quarterly">Trimestral</option><option value="semiannual">Semestral</option><option value="annual">Anual</option></select></Field>}<Field label="Preço base opcional (€)"><input type="number" step="0.01" className={inputClass} value={value.defaultAmountCents==null?"":value.defaultAmountCents/100} onChange={(e)=>setValue({...value,defaultAmountCents:e.target.value?Math.round(Number(e.target.value)*100):null})}/></Field><Field label="Horas estimadas"><input type="number" className={inputClass} value={value.estimatedHours??""} onChange={(e)=>setValue({...value,estimatedHours:e.target.value?Number(e.target.value):null})}/></Field><Field label="Custo interno (€)"><input type="number" step="0.01" className={inputClass} value={value.internalCostCents==null?"":value.internalCostCents/100} onChange={(e)=>setValue({...value,internalCostCents:e.target.value?Math.round(Number(e.target.value)*100):null})}/></Field></div><Field label="Descrição"><textarea rows={4} className={inputClass} value={value.description} onChange={(e)=>setValue({...value,description:e.target.value})}/></Field><Actions saving={saving} onClose={onClose} onSave={()=>onSave(value)}/></Modal>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl border border-white/10 bg-[#0b0f16] p-6"><div className="mb-5 flex justify-between"><h2 className="text-xl font-semibold">{title}</h2><button onClick={onClose}><X size={18}/></button></div>{children}</div></div>}
function Actions({saving,onClose,onSave}:{saving:boolean;onClose:()=>void;onSave:()=>void}){return <div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-white/10 px-4 py-2 text-xs">Cancelar</button><button disabled={saving} onClick={onSave} className="rounded-xl bg-cyan-300 px-4 py-2 text-xs font-semibold text-slate-950">{saving?"A guardar…":"Guardar"}</button></div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-[10px] uppercase tracking-wider text-white/35">{label}<div className="mt-1">{children}</div></label>}
function Empty({text}:{text:string}){return <div className="rounded-3xl border border-dashed border-white/10 p-12 text-center text-sm text-white/30">{text}</div>}
function Badge({children}:{children:React.ReactNode}){return <span className="rounded-full border border-cyan-300/15 bg-cyan-300/[.05] px-2.5 py-1 text-[9px] uppercase tracking-wider text-cyan-100/65">{children}</span>}
